### ISSUE TITLE
GPU info is not correct

### ISSUE THREAD

**Issue by yogurt7771** [Levminer/cores#10]
Left is from Windows Task Manager

![image](https://github.com/Levminer/cores/assets/22412010/cda920b3-7fe4-469e-9018-fbcc827be419)

**Comment by Levminer** [comment]
Hi!

Thanks for the report. What version are you using? Can you include the debug report .txt? (Left menu > Settings > Debug report)

**Comment by yogurt7771** [comment]
[cores-debug.txt](https://github.com/Levminer/cores/files/13737505/cores-debug.txt)
I am using the latest version

**Comment by Levminer** [comment]
Fixed in 0.16.0
