### ISSUE TITLE
Can't open GPU Info

### ISSUE THREAD

**Issue by MetaException** [Levminer/cores#12]
This error occurs when opening the GPU tab

I'm using the latest version from windows store

![brave_VhlDPUmeuA](https://github.com/Levminer/cores/assets/67053613/8a48fdec-15a6-416a-921c-94e7a4935f9d)

**Comment by Levminer** [comment]
Can you send your debug info? Settings > Debug info. It should be saved to your desktop.

**Comment by MetaException** [comment]
[cores-debug.txt](https://github.com/Levminer/cores/files/14887930/cores-debug.txt)
