### ISSUE TITLE
Cores not connecting remotly to Edge

### ISSUE THREAD

**Issue by RicanPR** [Levminer/cores#14]
App does not connect remotly to edge browser

**Comment by RicanPR** [comment]
[cores-debug.txt](https://github.com/Levminer/cores/files/14985468/cores-debug.txt)

**Comment by Levminer** [comment]
Thanks for the report! I'm currently rewriting the app/server/web communication, I will update this github issue when its ready.

**Comment by Levminer** [comment]
Related: 

https://groups.google.com/g/discuss-webrtc/c/Nm5BnQaF9x0
https://github.com/sipsorcery-org/sipsorcery/issues/1104
