### ISSUE TITLE
can you monitor apple silicon?

### ISSUE THREAD

**Issue by louis030195** [Levminer/cores#20]
like https://github.com/tlkh/asitop

curious if you found way to do so? metal api? mlcore?

**Comment by Levminer** [comment]
Hello,

Yes, the mac version will use something like asitop, but it will work without sudo. Currently I'm working on the linux version, after that I will start working on the mac version.

**Comment by Levminer** [comment]
Its still in beta, you can get the beta version here: https://nightly.link/Levminer/cores/actions/runs/11691943882/cores-macos-ARM64.zip
