### ISSUE TITLE
Question: Remote monitoring SW stack

### ISSUE THREAD

**Issue by EFeru** [Levminer/cores#28]
Hi Lorik,

Very cool app you created. If you don't mind, may I ask how you implemented the remote monitoring feature Tauri app <-> Web browser? I would like to make something similar for completely different Tauri app. If you don't want to give details, I understand.

Thank you for your help,
Emanuel

**Comment by Levminer** [comment]
It's based on WebRTC, I also created a library it's based on that. https://github.com/Levminer/ezrtc

**Comment by EFeru** [comment]
Nice. First time I hear about WebRTC. Thanks for providing your work on the topic. I will have a look.
